export const FETCH_CATEGORY = 'FETCH_CATEGORY'

export const FETCH_CATE_LIST = 'FETCH_CATE_LIST'

export const FETCH_CATE_INFO = 'FETCH_CATE_INFO'

export const FETCH_FOOD_DETAIL = 'FETCH_FOOD_DETAIL'

export const FETCH_FOOD_LOCATION = 'FETCH_FOOD_LOCATION'

export const FETCH_NEWS = 'FETCH_NEWS'

export const FETCH_PAGE= 'FETCH_PAGE'